package com.xr.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xr.happyFamily.jia.pojo.TimeTask;

import com.xr.database.dao.TimeTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timeTaskDaoConfig;

    private final TimeTaskDao timeTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timeTaskDaoConfig = daoConfigMap.get(TimeTaskDao.class).clone();
        timeTaskDaoConfig.initIdentityScope(type);

        timeTaskDao = new TimeTaskDao(timeTaskDaoConfig, this);

        registerDao(TimeTask.class, timeTaskDao);
    }
    
    public void clear() {
        timeTaskDaoConfig.clearIdentityScope();
    }

    public TimeTaskDao getTimeTaskDao() {
        return timeTaskDao;
    }

}
