package com.xr.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xr.happyFamily.pojo.DeviceChild;
import com.xr.happyFamily.pojo.DeviceGroup;

import com.xr.database.dao.DeviceChildDao;
import com.xr.database.dao.DeviceGroupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceChildDaoConfig;
    private final DaoConfig deviceGroupDaoConfig;

    private final DeviceChildDao deviceChildDao;
    private final DeviceGroupDao deviceGroupDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceChildDaoConfig = daoConfigMap.get(DeviceChildDao.class).clone();
        deviceChildDaoConfig.initIdentityScope(type);

        deviceGroupDaoConfig = daoConfigMap.get(DeviceGroupDao.class).clone();
        deviceGroupDaoConfig.initIdentityScope(type);

        deviceChildDao = new DeviceChildDao(deviceChildDaoConfig, this);
        deviceGroupDao = new DeviceGroupDao(deviceGroupDaoConfig, this);

        registerDao(DeviceChild.class, deviceChildDao);
        registerDao(DeviceGroup.class, deviceGroupDao);
    }
    
    public void clear() {
        deviceChildDaoConfig.clearIdentityScope();
        deviceGroupDaoConfig.clearIdentityScope();
    }

    public DeviceChildDao getDeviceChildDao() {
        return deviceChildDao;
    }

    public DeviceGroupDao getDeviceGroupDao() {
        return deviceGroupDao;
    }

}
