package com.xr.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xr.happyFamily.le.pojo.DerailResult;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DERAIL_RESULT".
*/
public class DerailResultDao extends AbstractDao<DerailResult, Long> {

    public static final String TABLENAME = "DERAIL_RESULT";

    /**
     * Properties of entity DerailResult.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DerailName = new Property(1, String.class, "derailName", false, "DERAIL_NAME");
        public final static Property DerailId = new Property(2, int.class, "derailId", false, "DERAIL_ID");
        public final static Property CreateTime = new Property(3, long.class, "createTime", false, "CREATE_TIME");
        public final static Property DerailResult = new Property(4, int.class, "derailResult", false, "DERAIL_RESULT");
        public final static Property DerailPo = new Property(5, int.class, "derailPo", false, "DERAIL_PO");
    }


    public DerailResultDao(DaoConfig config) {
        super(config);
    }
    
    public DerailResultDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DERAIL_RESULT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DERAIL_NAME\" TEXT," + // 1: derailName
                "\"DERAIL_ID\" INTEGER NOT NULL ," + // 2: derailId
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 3: createTime
                "\"DERAIL_RESULT\" INTEGER NOT NULL ," + // 4: derailResult
                "\"DERAIL_PO\" INTEGER NOT NULL );"); // 5: derailPo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DERAIL_RESULT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DerailResult entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String derailName = entity.getDerailName();
        if (derailName != null) {
            stmt.bindString(2, derailName);
        }
        stmt.bindLong(3, entity.getDerailId());
        stmt.bindLong(4, entity.getCreateTime());
        stmt.bindLong(5, entity.getDerailResult());
        stmt.bindLong(6, entity.getDerailPo());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DerailResult entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String derailName = entity.getDerailName();
        if (derailName != null) {
            stmt.bindString(2, derailName);
        }
        stmt.bindLong(3, entity.getDerailId());
        stmt.bindLong(4, entity.getCreateTime());
        stmt.bindLong(5, entity.getDerailResult());
        stmt.bindLong(6, entity.getDerailPo());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DerailResult readEntity(Cursor cursor, int offset) {
        DerailResult entity = new DerailResult( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // derailName
            cursor.getInt(offset + 2), // derailId
            cursor.getLong(offset + 3), // createTime
            cursor.getInt(offset + 4), // derailResult
            cursor.getInt(offset + 5) // derailPo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DerailResult entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDerailName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDerailId(cursor.getInt(offset + 2));
        entity.setCreateTime(cursor.getLong(offset + 3));
        entity.setDerailResult(cursor.getInt(offset + 4));
        entity.setDerailPo(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DerailResult entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DerailResult entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DerailResult entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
